import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

type TextNode = string | { text: string } | { join: TextNode[] } | { quote: TextNode };

/** Expand visible literal text, concatenation and JSON string quoting only.
 * Embedded evidence is never parsed, normalized or regenerated by this loader.
 */
export function readTextFixture(path: URL): string {
  const dictionary = JSON.parse(readFileSync(path, 'utf8')) as {
    format: string;
    nodes: Record<string, TextNode>;
    files: { root: string; bytes: number; sha256: string }[];
  };
  assert.equal(dictionary.format, 'rcl-fixture-text-dictionary-v1');
  assert.equal(dictionary.files.length, 1);
  const file = dictionary.files[0]!;
  const memo = new Map<string, string>(), active = new Set<string>();
  function expand(node: TextNode): string {
    if (typeof node === 'string') {
      if (memo.has(node)) return memo.get(node)!;
      assert(!active.has(node) && Object.hasOwn(dictionary.nodes, node), 'invalid text reference');
      active.add(node);
      const bytes = expand(dictionary.nodes[node]!);
      active.delete(node); memo.set(node, bytes);
      return bytes;
    }
    assert.equal(Object.keys(node).length, 1);
    let bytes: string;
    if ('text' in node) { assert.equal(typeof node.text, 'string'); bytes = node.text; }
    else if ('join' in node) { assert(Array.isArray(node.join)); bytes = node.join.map(expand).join(''); }
    else { assert('quote' in node); bytes = JSON.stringify(expand(node.quote)); }
    assert(Buffer.byteLength(bytes) <= file.bytes, 'text exceeds declared size');
    return bytes;
  }
  const bytes = expand(file.root);
  assert.equal(Buffer.byteLength(bytes), file.bytes);
  assert.equal(createHash('sha256').update(bytes).digest('hex'), file.sha256);
  return bytes;
}
