import { createHash } from 'node:crypto';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { withNativeTarget } from '../../src/converge/target-ownership.js';
import { CheckpointJournal, freezeCheckpointPlan } from '../../src/dispatch/checkpoint.js';
import { createOriginalLaunch, encodeOriginalLaunch } from '../../src/dispatch/original-launch.js';
import { createVerificationLateAudit } from '../../src/dispatch/verification-late-audit.js';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(p => rm(p, { recursive: true, force: true }))); });
const target = 'allocator-one/rcl#105', runId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', hash = (v: string) => createHash('sha256').update(v).digest('hex');
async function fixture(terminal = true) { const dir = await realpath(await mkdtemp(join(tmpdir(), 'rcl-vlate-'))); roots.push(dir); const plan = freezeCheckpointPlan({ target, headSha: 'a'.repeat(40), mergeBaseSha: 'b'.repeat(40), patchSha256: 'c'.repeat(64), configSha256: 'd'.repeat(64), specSha256: 'e'.repeat(64), contextSha256: '3'.repeat(64), toolsSha256: '4'.repeat(64), parser: { name: 'p', version: 1 }, roster: [{ seat: 's', model: 'm', role: 'r', route: 'openai' }], chunks: [{ index: 0, total: 1, digest: hash('c') }], prompts: [{ seat: 's', chunk: 0, systemSha256: hash('s'), userSha256: hash('u') }] }); let journal!: CheckpointJournal; await withNativeTarget(dir, target, async (owner) => { journal = await CheckpointJournal.create({ commonDir: dir, namespace: 'vlate', plan, ownership: owner }); const launch = createOriginalLaunch({ runId, target, originalNativeClaim: { attempt: 1, round: 1 }, capturedInputsSha256: hash('capture'), planDigest: plan.digest, startedAtMs: 1, expiresAtMs: 1000, maxPhysicalCalls: 1, maxAttemptsPerCell: 1 }); await journal.bind('captured-inputs', 'capture', owner); await journal.bind('launch', encodeOriginalLaunch(launch), owner); await journal.recordIntent('s:0', { id: 'review', kind: 'unknown' }, owner); await journal.finalize(owner); await journal.beginVerification({ runId, gatingPlanBytes: '{"batches":[{"findingIndices":[0],"systemPrompt":"sys","userPrompt":"usr"}],"candidateIndices":[0],"findings":[],"initialGating":[],"model":"m","verificationPassTimeoutMs":10,"verificationTimeoutMs":10,"version":1}', model: 'm', provider: 'openai', batches: [{ systemPrompt: 'sys', userPrompt: 'usr' }], startedAtMs: 2, expiresAtMs: 12, verificationTimeoutMs: 10, verificationPassTimeoutMs: 10, maxPhysicalCalls: 1 }, owner); await journal.recordVerificationIntent({ batchIndex: 0, attemptId: 'verify', startedAtMs: 3 }, owner); if (terminal)
    await journal.finalizeVerification({ status: 'failed', finishedAtMs: 12, reason: 'timeout' }, owner); }); return { dir, journal }; }
const result = (text = 'ok') => ({ batchIndex: 0, attemptId: 'verify', finishedAtMs: 13, answerBytes: JSON.stringify({ model: 'm', provider: 'openai', text, status: 'success', durationMs: 1 }) });
describe('late verifier audit', () => { it('refuses writes before verifier terminal', async () => { const f = await fixture(false); await expect(withNativeTarget(f.dir, target, owner => f.journal.recordLateVerificationResult(result(), owner))).rejects.toThrow('checkpoint_verification_late_requires_terminal'); }); it('rejects a conflicting repeated late result', async () => { const f = await fixture(); await withNativeTarget(f.dir, target, owner => f.journal.recordLateVerificationResult(result(), owner)); await expect(withNativeTarget(f.dir, target, owner => f.journal.recordLateVerificationResult(result('changed'), owner))).rejects.toThrow('checkpoint_verification_late_conflict'); }); it('buffers then activates under original ownership', async () => { const f = await fixture(); await withNativeTarget(f.dir, target, async (owner) => { const audit = createVerificationLateAudit({ commonDir: f.dir, journal: f.journal, ownership: owner, onError: () => { throw new Error('sink'); } }); await audit.accept(result()); await expect(audit.drain()).rejects.toThrow('late_verification_audit_requires_terminal'); await audit.flushAfterFinalization(); expect((await f.journal.readLateVerificationAudit())).toHaveLength(1); }); }); it('retains an exact post-terminal answer without changing phase proof and rejects conflicts', async () => { const f = await fixture(); const before = await f.journal.exportVerificationProof(), saved = result(); await withNativeTarget(f.dir, target, async (owner) => { await f.journal.recordLateVerificationResult(saved, owner); await f.journal.recordLateVerificationResult(saved, owner); }); const audit = await f.journal.readLateVerificationAudit(); expect(audit).toHaveLength(1); expect(audit[0]!.result.answerBytes).toBe(result().answerBytes); expect(await f.journal.exportVerificationProof()).toEqual(before); }); });
