import { createHash } from 'node:crypto';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { CheckpointJournal, exportCheckpointProof, freezeCheckpointPlan, type CheckpointProof } from '../../src/dispatch/checkpoint.js';
import { captureReviewerInputs } from '../../src/dispatch/captured-inputs.js';
import { createOriginalLaunch, encodeOriginalLaunch } from '../../src/dispatch/original-launch.js';
import { createRecoveryOperation, encodeRecoveryOperation } from '../../src/dispatch/recovery-operation.js';
import { withNativeTarget } from '../../src/converge/target-ownership.js';
import { captureAggregationInputs, AGGREGATION_ALGORITHM } from '../../src/report/aggregation-inputs.js';
import { projectCheckpointReport } from '../../src/report/checkpoint-projection.js';
import { deriveCheckpointConsensus, type CheckpointAssemblyInput } from '../../src/report/checkpoint-assembly.js';
import { captureSupplementalAsync } from '../../src/report/supplemental-async.js';
import { configDigest, diffDigest, sha256Hex, stableStringify } from '../../src/report/run-header.js';
import { planGating } from '../../src/consensus/gating.js';
import { deriveCheckpointGating } from '../../src/report/checkpoint-gating.js';
const roots: string[] = []; afterEach(async () => { await Promise.all(roots.splice(0).map(x => rm(x,{recursive:true,force:true}))); });
const target='allocator-one/rcl#105', runId='11111111-1111-4111-8111-111111111111', hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const role={name:'general',systemPrompt:'s',description:'d',focus:[],isSpecialized:false};
const thresholds={minConsensusScore:0,minConfidence:0,dedupeLineWindow:5,jaccardThreshold:0.3};
function finding(file='a.ts'){return {id:'f',file,startLine:1,endLine:1,severity:'important' as const,category:'correctness',title:'guard missing',description:'guard missing'};}
async function fixture(opts:{mode?:'verified-consensus'|'all-findings'; both?:boolean; second?:boolean; file?:string; asyncLaunched?:number; id?:string; minScore?:number; unknownSecond?:boolean; seats?:number; minConfidence?:number}={}) {
 const fixtureRunId=opts.id??runId;
 const localThresholds={...thresholds,minConsensusScore:opts.minScore??thresholds.minConsensusScore,minConfidence:opts.minConfidence??thresholds.minConfidence};
 const seats=opts.seats??2;
 const dir=await realpath(await mkdtemp(join(tmpdir(),'cgating-')));roots.push(dir); const diff:any={source:'local',files:[{filename:'a.ts',status:'modified',patch:'@@ -1 +1 @@\n-x\n+y',additions:1,deletions:1,language:'ts'}]};
 const config:any={quorumFraction:1,thresholds:localThresholds,output:{belowThresholdAppendix:true}}; const tools=stableStringify({parser:{name:'findings-json',version:1},aggregation:AGGREGATION_ALGORITHM});
 const plan=freezeCheckpointPlan({target,headSha:'a'.repeat(40),mergeBaseSha:'b'.repeat(40),patchSha256:diffDigest(diff.files),configSha256:configDigest(config),specSha256:hash('spec'),contextSha256:hash('[]'),toolsSha256:hash(tools),parser:{name:'findings-json',version:1},roster:Array.from({length:seats},(_,i)=>({seat:`s${i}`,model:`m${i}`,role:'general',route:'openai'})),chunks:[{index:0,total:1,digest:hash('chunk')}],prompts:Array.from({length:seats},(_,i)=>({seat:`s${i}`,chunk:0,systemSha256:hash('s'),userSha256:hash('u')}))});
 const aggregation=captureAggregationInputs({algorithm:AGGREGATION_ALGORITHM,diffSha256:plan.patchSha256,roleMap:new Map([['general',role]]),thresholds:localThresholds,gating:{mode:opts.mode??'verified-consensus',minModels:2,verificationModel:'openai/verifier',verificationTimeoutMs:100,verificationPassTimeoutMs:500},modelWeights:new Map(Array.from({length:seats},(_,i)=>[`m${i}`,1])),belowThresholdAppendix:true});
 const captured=captureReviewerInputs({plan,policy:{version:1,fraction:1},patchBytes:stableStringify(diff.files.map((f:any)=>({filename:f.filename,status:f.status,previousFilename:null,patch:f.patch,additions:f.additions,deletions:f.deletions,blobSha:null}))),configBytes:stableStringify(config),specBytes:'spec',contextBytes:'[]',toolsBytes:tools,chunkBytes:['chunk'],assignments:plan.cells.map(c=>({model:c.model,provider:c.route,role})),prompts:plan.cells.map(()=>({systemPrompt:'s',userPrompt:'u'})),aggregation});
 let journal!:CheckpointJournal; let proof!:CheckpointProof;
 await withNativeTarget(dir,target,async owner=>{journal=await CheckpointJournal.create({commonDir:dir,namespace:'run',plan,ownership:owner}); await journal.bind('captured-inputs',captured.bytes,owner); await journal.bind('launch',encodeOriginalLaunch(createOriginalLaunch({runId:fixtureRunId,target,originalNativeClaim:{attempt:1,round:1},capturedInputsSha256:hash(captured.bytes),planDigest:plan.digest,startedAtMs:1,expiresAtMs:1000,maxPhysicalCalls:4,maxAttemptsPerCell:1})),owner); for(const i of Array.from({length:seats},(_,i)=>i)) {if(opts.second===false&&i===1) continue;const review={model:`m${i}`,role:'general',provider:'openai',status:'success' as const,durationMs:1,findings:i===0?[finding(opts.file),...(opts.both?[{...finding('b.ts'),id:'dropped',severity:'minor' as const,title:'other guard',description:'other guard',startLine:5,endLine:5}]:[])]:opts.both?[finding(opts.file),{...finding('b.ts'),id:'dropped',severity:'minor' as const,title:'other guard',description:'other guard',startLine:5,endLine:5}]:[]};const paidAttempt={id:`r${i}`,kind:(opts.unknownSecond&&i===1?'unknown':'paid')} as const;await journal.recordIntent(`s${i}:0`,paidAttempt,owner);if(!(opts.unknownSecond&&i===1))await journal.recordResult(`s${i}:0`,paidAttempt,{kind:'success',chunk:0,reviewBytes:JSON.stringify(review)},owner);} await journal.finalize(owner);proof=await exportCheckpointProof(journal);});
 const assembly:CheckpointAssemblyInput={projection:projectCheckpointReport({sources:[],successor:{runId:fixtureRunId,proof},policy:{version:1,fraction:1}}),supplementalAsync:captureSupplementalAsync([],opts.asyncLaunched??0),diff,startTime:1,run:{id:fixtureRunId,rclVersion:'x',command:'review',target:{kind:'pr',repo:'allocator-one/rcl',prNumber:105,headSha:plan.headSha},roster:plan.roster.map(s=>({model:s.model,role:s.role,provider:s.route,lane:'blocking' as const})),spec:{source:'flag',sha256:plan.specSha256},contextFiles:[],runner:{kind:'agent'},startedAt:new Date(1),converge:{target,attempt:1,round:1}}};
 return {dir,journal,assembly,plan,captured,proof};
}
async function successorFixture(inheritedAsync: number) {
 const source=await fixture({mode:'all-findings'}), successorRunId='33333333-3333-4333-8333-333333333333'; let journal!:CheckpointJournal; let proof!:CheckpointProof;
 await withNativeTarget(source.dir,target,async owner=>{const operation=createRecoveryOperation({operationId:'44444444-4444-4444-8444-444444444444',successorRunId,sourceRunId:source.assembly.run.id,sourceReportSha256:hash('source-report'),sourceCheckpointSha256:source.proof.digest,capturedInputsSha256:hash(source.captured.bytes),planDigest:source.plan.digest,target,originalNativeClaim:{attempt:1,round:1},successorNativeClaim:{attempt:2,round:1},startedAtMs:2,expiresAtMs:1000,maxAdditionalCalls:1,maxAttemptsPerCell:1});journal=await CheckpointJournal.create({commonDir:source.dir,namespace:successorRunId,plan:source.plan,ownership:owner});await journal.bind('captured-inputs',source.captured.bytes,owner);await journal.bind('source',stableStringify({run_id:source.assembly.run.id,report_sha256:hash('source-report'),checkpoint_sha256:source.proof.digest}),owner);await journal.bind('operation',encodeRecoveryOperation(operation),owner);await journal.finalize(owner);proof=await exportCheckpointProof(journal);});
 return {...source,assembly:{...source.assembly,projection:projectCheckpointReport({sources:[{runId:source.assembly.run.id,proof:source.proof}],successor:{runId:successorRunId,proof},policy:{version:1,fraction:1}}),supplementalAsync:captureSupplementalAsync([],inheritedAsync),run:{...source.assembly.run,id:successorRunId,converge:{target,attempt:2,round:1}}} as CheckpointAssemblyInput};
}
async function phase(f:Awaited<ReturnType<typeof fixture>>, kind:'complete'|'failed'='complete', mutate=false, capped=false){const d=deriveCheckpointConsensus(f.assembly);const p=planGating(d.consensus.reportFindings,{minModels:2,verificationModel:'openai/verifier',verificationTimeoutMs:100,verificationPassTimeoutMs:500,diffFiles:f.assembly.diff.files,modelWeights:new Map([['m0',1],['m1',1]])});const plan=mutate?{...p,findings:p.findings.map(x=>({...x,title:'other'}))}:p;const saved={runId:f.assembly.run.id,gatingPlanBytes:stableStringify(plan),model:plan.model,provider:'openai',batches:plan.batches.map(({systemPrompt,userPrompt})=>({systemPrompt,userPrompt})),startedAtMs:2,expiresAtMs:502,verificationTimeoutMs:100,verificationPassTimeoutMs:500,maxPhysicalCalls:capped ? 0 : plan.batches.length};await withNativeTarget(f.dir,target,async owner=>{await f.journal.beginVerification(saved,owner);for(const [i] of plan.batches.entries()){if(capped) break;await f.journal.recordVerificationIntent({batchIndex:i,attemptId:`v${i}`,startedAtMs:3},owner);if(kind==='complete')await f.journal.recordVerificationResult({batchIndex:i,attemptId:`v${i}`,finishedAtMs:4,answerBytes:JSON.stringify({model:'openai/verifier',provider:'openai',status:'success',durationMs:1,text:'[{"id":"F1","verdict":"confirmed"}]'})},owner);}await f.journal.finalizeVerification(kind==='complete'?{status:'complete',finishedAtMs:5}:{status:'failed',finishedAtMs:5,reason:'failed'},owner);});return f.journal.exportVerificationProof();}
describe('checkpoint gating candidate',()=>{
 it('requires and replays exact complete phase proof without a live ask',async()=>{const f=await fixture();const p=await phase(f);const r=deriveCheckpointGating(f.assembly,p);expect(r.disposition).toBe('replayed');expect(r.findings[0]!.gating?.reason).toBe('verified');expect(r.verification?.unrefuted).toBe(1);});
 it('refuses missing, changed, and cross-run phase proof',async()=>{const f=await fixture();expect(()=>deriveCheckpointGating(f.assembly)).toThrow('checkpoint_gating_missing_phase');const p=await phase(f);expect(()=>deriveCheckpointGating(f.assembly,{...p,digest:'0'.repeat(64)})).toThrow('checkpoint_gating_invalid_phase');const other=await fixture({id:'22222222-2222-4222-8222-222222222222'});const foreign=await phase(other);expect(()=>deriveCheckpointGating(f.assembly,foreign)).toThrow();});
 it('uses strict unannotated fallback only for a valid sealed failed phase',async()=>{const f=await fixture();const p=await phase(f,'failed');const r=deriveCheckpointGating(f.assembly,p);expect(r.disposition).toBe('strict_fallback');expect(r.findings[0]!.gating).toBeUndefined();expect(r.verification).toBeUndefined();});
 it('rejects a sealed phase whose regenerated plan differs, but accepts a failed zero-cap phase',async()=>{const f=await fixture();const p=await phase(f,'complete',true);expect(()=>deriveCheckpointGating(f.assembly,p)).toThrow('checkpoint_gating_plan_mismatch');const capped=await fixture();const q=await phase(capped,'failed',false,true);expect(deriveCheckpointGating(capped.assembly,q).disposition).toBe('strict_fallback');});
 it('keeps deterministic annotations and rejects phase for no-batch candidate paths',async()=>{const noCandidate=await fixture({both:true});const a=deriveCheckpointGating(noCandidate.assembly);expect(a.disposition).toBe('deterministic');expect(a.findings[0]!.gating?.reason).toBe('consensus');const unavailable=await fixture({file:'other.ts'});const b=deriveCheckpointGating(unavailable.assembly);expect(b.findings[0]!.gating?.verification?.verdict).toBe('unavailable');const forbidden=await phase(noCandidate);expect(()=>deriveCheckpointGating(noCandidate.assembly,forbidden)).toThrow('checkpoint_gating_phase_not_applicable');});
 it('annotates actual dropped appendix findings after deterministic gating only',async()=>{const f=await fixture({both:true,seats:3,minConfidence:.9});const r=deriveCheckpointGating(f.assembly);expect(r.disposition).toBe('deterministic');expect(r.appendix).toHaveLength(1);expect(r.appendix[0]!.gating).toEqual({reason:'none'});});
 it('enforces current original reviewer and async count even when gating is plain',async()=>{const f=await fixture({mode:'all-findings',asyncLaunched:499,unknownSecond:true});expect(()=>deriveCheckpointGating(f.assembly)).toThrow('checkpoint_gating_call_cap');});
 it('does not rebill inherited async or source attempts on a successor',async()=>{const successor=await successorFixture(500);expect(deriveCheckpointGating(successor.assembly).disposition).toBe('plain');});
 it('returns plain output and refuses phases for all-findings and inconclusive evidence',async()=>{const all=await fixture({mode:'all-findings'});expect(deriveCheckpointGating(all.assembly).disposition).toBe('plain');const p=await phase(all);expect(()=>deriveCheckpointGating(all.assembly,p)).toThrow('checkpoint_gating_phase_not_applicable');const inconclusive=await fixture({second:false});expect(deriveCheckpointGating(inconclusive.assembly).disposition).toBe('plain');const q=await phase(inconclusive);expect(()=>deriveCheckpointGating(inconclusive.assembly,q)).toThrow('checkpoint_gating_phase_not_applicable');});
});
